### ISSUE TITLE
Breaking changes to source data files

### ISSUE THREAD

**Issue by elmorg** [louisdecharson/covid-19#2]
See deprecated waring here - https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_time_series

More details on the new data structure here - https://github.com/CSSEGISandData/COVID-19/issues/1250 . 

The main issue is that the recovered data is now missing.

**Comment by louisdecharson** [comment]
Thank you very much for letting me know. 
I've accordingly removed recovered cases from the page -> https://github.com/louisdecharson/covid-19/commit/37349a3aed6a4d2816c2cd41fd95910a0a783687.

I'll add testing once it's available !
